### ISSUE TITLE
Typing text will remove next variable

### ISSUE THREAD

**Issue by andreasdc** [eclipse-platform/.github#100]
When you have for example
if (object.var)
and you want to type newobject. before the object, it will remove "object" text.

**Comment by merks** [comment]
The part it's about to replace turns yellow when you do this right?

I think this is controlled by Window -> Preferences -> Java -> Editor -> Content Assist  Insertion option Completion inserts versus Completion Overwrites.

Which setting do you have and have you tried the other setting?

**Comment by andreasdc** [comment]
Yes it turns yellow.
I had overwrites option.
The other one works perfect I think, thank you! ❤️

**Comment by merks** [comment]
Yes, I'm not a big fan of the writing behavior.
