### ISSUE TITLE
Opening the wrong source

### ISSUE THREAD

**Issue by andreasdc** [eclipse-platform/.github#102]
When I open reference using F3 it shows source code from libraries not from the project list.

**Comment by merks** [comment]
Is there are correct source from the project list to which it should navigate instead?  Or are you expecting F3 to do nothing when it's possible to find source elsewhere than on the project list?

**Comment by andreasdc** [comment]
Oh I think it's duplicated issue, you can check https://github.com/eclipse-platform/.github/issues/101
