### ISSUE TITLE
Add a yml editor to the Oomph Platform SDK setup

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/.github#107]
As we now have more and more ymal file (most notable github workflows), it seems usefull to have an editor to edit them.

Can we add https://marketplace.eclipse.org/content/yaml-editor (or similar) to the platform SDK?

I tried to drag+drop the marketplace link but have not had success with that.

**Comment by akurtakov** [comment]
https://github.com/eclipse/wildwebdeveloper/ also has yaml editor, maybe you'll have better luck with it.

 Aggregating platform SDK is already enough trouble to introduce extra obstacles. I think platform SDK to contain only things just build to prevent the case where build fails due to change needed in 3rd party against unreleased version (aka build cycle).  For the purpose you're looking there is https://www.eclipse.org/downloads/packages/release/2023-03/r/eclipse-ide-eclipse-committers so such out-of-the-box experience is provided for committer. I actually believe it contains yaml editor already.

**Comment by laeubi** [comment]
@akurtakov just to be sure I mean the automatic setup for develop platform not the "sdk.zip"

**Comment by mickaelistria** [comment]
So it's not the SDK but the Oomph configuration?

**Comment by iloveeclipse** [comment]
> just to be sure I mean the automatic setup for develop platform not the

So probably you want change title of this task, because I also misunderstood it, same way as Alex.

**Comment by merks** [comment]
It's easy to add additional tools to be installed to the Oomph setup.  Here are some examples:

![image](https://user-images.githubusercontent.com/208716/226548666-3c462cc2-a669-402b-a3c6-6153756107f1.png)

**Comment by laeubi** [comment]
> So it's not the SDK but the Oomph configuration?

The window titlte [of this](https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#create-an-eclipse-development-environment) is 
![grafik](https://user-images.githubusercontent.com/1331477/226548601-b82f6364-dd23-47d6-ba00-c4d28e8e2998.png)

Also the website name it "Platform SDK" so I'm not sure what is the official name for it?!?

![grafik](https://user-images.githubusercontent.com/1331477/226548919-6230f9d7-3a9a-4a16-bada-25756169fda7.png)

**Comment by merks** [comment]
The title now makes it clear that you don't want to add it to the SDK product/feature but rather to the setup of the development environment.  Which update site contains the feature(s) that you want installed?

**Comment by laeubi** [comment]
I only found the Marketplace entry but not an update site: https://marketplace.eclipse.org/content/yaml-editor

**Comment by akurtakov** [comment]
Isn't https://download.eclipse.org/wildwebdeveloper/releases/latest/ working  for you? I ask as this is an EF project with some platform committers working on it too so communication channel and rules should be fairly similar.

**Comment by merks** [comment]
We could also just define a content type binding to an editor. Which one would be good?

**Comment by merks** [comment]
@laeubi 

I could add this:
```
<?xml version="1.0" encoding="UTF-8"?>
<workbench:FileAssociationsTask
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:workbench="http://www.eclipse.org/oomph/setup/workbench/1.0"
    xsi:schemaLocation="http://www.eclipse.org/oomph/setup/workbench/1.0 http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/setups/models/Workbench.ecore">
  <mapping filePattern="*.yml"
      defaultEditorID="org.eclipse.ui.genericeditor.GenericEditor"/>
  <mapping filePattern="*.json"
      defaultEditorID="org.eclipse.ui.genericeditor.GenericEditor"/>
</workbench:FileAssociationsTask>
```
I'm not sure if there were a more specific installed editor bound to that extension if this would override that.  For me, both these things opened in a regular text editor already anyway.  

Shall I go ahead and add this to the setup?

**Comment by laeubi** [comment]
It would at laest be better than the current default, maybe @akurtakov can explain how e can use a wwd editor.

**Comment by laeubi** [comment]
So can we probably add WWD as well? I think syntax highlight and probably content assist would be great.

**Comment by merks** [comment]
@laeubi 

I'm slightly uncomfortable installing WWD because not everyone needs that and it might introduce behavior that one might attribute to the SDK itself.  (I.e., when eating your own dog food you're not sure which dog food you're eating.)

You could instead do the following.  Copy the text below to the clipboard, use Navigate -> Open Setup -> User to open the Setup Editor for your user.setup, and paste the following p2 task to your User object in the editor:
```
<?xml version="1.0" encoding="UTF-8"?>
<setup.p2:P2Task
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:setup.p2="http://www.eclipse.org/oomph/setup/p2/1.0"
    label="WWD">
  <requirement
      name="org.eclipse.wildwebdeveloper.feature.feature.group"/>
  <requirement
      name="org.eclipse.wildwebdeveloper.xml.feature.feature.group"/>
  <repository
      url="https://download.eclipse.org/wildwebdeveloper/releases/latest/"/>
</setup.p2:P2Task>
```
Then every IDE you install (or already have installed) with Oomph will automatically install WWD.

You could even restrict the task to install only for the Eclipse SDK product:
```
<?xml version="1.0" encoding="UTF-8"?>
<setup.p2:P2Task
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:setup="http://www.eclipse.org/oomph/setup/1.0"
    xmlns:setup.p2="http://www.eclipse.org/oomph/setup/p2/1.0"
    label="WWD">
  <restriction
      xsi:type="setup:Product"
      href="index:/org.eclipse.setup#//@productCatalogs[name='org.eclipse.applications']/@products[name='eclipse.platform.sdk']"/>
  <requirement
      name="org.eclipse.wildwebdeveloper.feature.feature.group"/>
  <requirement
      name="org.eclipse.wildwebdeveloper.xml.feature.feature.group"/>
  <repository
      url="https://download.eclipse.org/wildwebdeveloper/releases/latest/"/>
</setup.p2:P2Task>
```
Is that okay?

**Comment by laeubi** [comment]
I'll try that out, given that we also have to edit html pages (N&N), WWD might still be useful for a wider audience.
