### ISSUE TITLE
Eclipse flatpack often crashes when closing the currently open tab

### ISSUE THREAD

**Issue by Schweiger-Jacob** [eclipse-platform/.github#110]
If you try to close the tab that's currently open eclipse will usually crash. Switching to another tab and then closing the tab works correctly though. This problem occurs on the flatpackage on the latest version of Linux mint.

**Comment by iloveeclipse** [comment]
- Please attach all error logs or stack traces or crash dump files you have.
- Please provide information about OS version, GTK3 version and if you use Wayland or X11

**Comment by Schweiger-Jacob** [comment]
[Untitled.log](https://github.com/eclipse-platform/.github/files/11104933/Untitled.log)
after further testing it only seems happens if I close the the current shortly after eclipse starts up 

i'm on Linux Mint 21.1 x86_64  
x11
Mint-Y-Dark [GTK2/3]

**Comment by jukzi** [comment]
```
java.lang.IllegalArgumentException
	at org.eclipse.jdt.core.dom.ASTNode.setSourceRange(ASTNode.java:3348)

```
not platform. please create issue at jdt.core
https://github.com/eclipse-jdt/eclipse.jdt.core/issues/
