### ISSUE TITLE
Cannot install via Eclipse Installer

### ISSUE THREAD

**Issue by diti0023** [eclipse-platform/.github#113]
When trying to install via drag & drop or copy & apply (from https://www.eclipse.org/setups/installer/?url=https://raw.githubusercontent.com/eclipse-platform/eclipse.platform.releng.aggregator/master/oomph/PlatformSDKConfiguration.setup&show=true) I get the following error:

Fetching content.xml from https://download.eclipse.org/eclipse/updates/4.28-I-builds/I20230416-1800/
ERROR: org.eclipse.equinox.p2.metadata.repository code=1000 No repository found at https://download.eclipse.org/webtools/CI/3.29.0/I-latest/repository.
  at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:405)
...

![Screenshot from 2023-04-18 09-04-12](https://user-images.githubusercontent.com/130975899/232698705-2e55bb9c-6daf-4e9c-bbc9-07a88af836e1.png)

**Comment by iloveeclipse** [comment]
Please change https://download.eclipse.org/webtools/CI/3.29.0/I-latest/repository/ update site to https://download.eclipse.org/webtools/CI/3.30.0/I-latest/repository/

**Comment by iloveeclipse** [comment]
OK, thanks.

**Comment by merks** [comment]
@diti0023 

Locally I see the changes are visible in my installer, so I think it should work for you now.  Thanks for reporting the issue!!
