### ISSUE TITLE
Oomph tries to install and use java 19 for java 17

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/.github#114]
As far as i know eclipse won't run arbitrary high java versions (if jdk removes deprecated things). however when i try to install Platform with oomp installer on a computer where it does not find java 17 (but 19) it will try to use 19:
![image](https://user-images.githubusercontent.com/51790620/232703826-b077b4f3-e462-4fcb-a003-742ba2eb87e4.png)

after selecting 17
![image](https://user-images.githubusercontent.com/51790620/232703908-e36ac5f5-6563-4515-b9d1-3cbcf639b45b.png)
i get asked in the next page where my 17 jdk is.  And it again preselects19, but does not offer the already selected 17:
![image](https://user-images.githubusercontent.com/51790620/232704163-31311e7a-021b-4cf1-9d0a-47887aa8790f.png)

**Comment by Bananeweizen** [comment]
I believe you are confusing some things.

The first JRE is the one running eclipse, i.e. the one referenced in the eclipse.ini vm argument. And its default is probably driven by the PATH or "used during last invocation".

On the variables page on the other hand you are asked for the JRE mapping being used for compilation (corresponding to Window>Prefs>Java>JRE Mappings). And that variable (or Java level) is specific to the setup you selected.

**Comment by merks** [comment]
Eclipse's run option https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fruntime-options.html specify this:

osgi.requiredJavaVersion
    The minimum java version that is required to launch Eclipse. The default value is "1.4.1".

Also all the BREEs in the bundles specify a minimum.

Nothing specifies an upper bound.  So as I know, there is no way know that something won't run on some arbitrary higher version, and I have tested with Java 21 and that works fine.
