### ISSUE TITLE
update EMF dependency to github

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/.github#122]
My OOmphed Platform Workspace still contains gerrit origin while repo was moved to https://github.com/eclipse-emf/org.eclipse.emf
![image](https://user-images.githubusercontent.com/51790620/233608335-ce2e363c-1f6e-4861-9012-b4cfdbdc5667.png)

**Comment by merks** [comment]
Indeed I overlooked to change that after EMF migrated!
