### ISSUE TITLE
.polyglot.META-INF

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/.github#128]
After working with oomphed commiters workspace i get unstaged changes without doing changes.

Can someone explain what those files are for and why they are not ignored by team provider?

![image](https://github.com/eclipse-platform/.github/assets/51790620/3a212d0e-c62b-41bd-92c0-3dfc73a13ad5)

**Comment by laeubi** [comment]
> Can someone explain what those files are for

https://github.com/takari/polyglot-maven

> why they are not ignored by team provider

Usually something like `.polyglot.*` in `.gitignore` is suitable enough
