### ISSUE TITLE
How long shall we keep maintenance branches?

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/.github#13]
All repos still have all maintenance branches, e.g. the 1.0 maintenance branch. We also have tags for all releases. Shall we decide that we only need x maintenance branches, e.g. the last 10 or 12 releases?

cc @akurtakov @sravanlakkimsetti

**Comment by akurtakov** [comment]
I think 1.0 and 2.0 branches can be closed without further discussions. The branches can't simply be deleted though - there have to be tags from latest commits on each e.g.  R2_0_maintenance_FINAL tag (better naming is welcome).

**Comment by iloveeclipse** [comment]
Just curious: what's wrong with old branches? Do you see any issues leave them "as is"?

**Comment by akurtakov** [comment]
All branches are consulted whether they are buildable by Jenkins jobs https://ci.eclipse.org/platform/job/eclipse.platform.ui/indexing/consoleText is what I know.

**Comment by vogella** [comment]
> If the history of changes remain after branch deletion, it's OK for me, otherwise not. There must be a good reason to delete something that can't be restored anymore.

We commits will be accessable via the suggested tags

**Comment by iloveeclipse** [comment]
I still miss a "good reason". Just because we can?

**Comment by vogella** [comment]
> I still miss a "good reason". Just because we can?

Because they are not used anymore.

**Comment by tjwatson** [comment]
I am against removing history for past releases.  Too many times being able to checkout the past has help me. So far I have not seen nearly enough justification to remove the maint branches.

**Comment by vogella** [comment]
@tjwatson sounds like you have a misunderstanding, we are not proposing to remove history, lets discuss in our next PMC call

**Comment by tjwatson** [comment]
In the past we have made releases off the maintenance branches.  Deleting such a branch deletes the history that went into that release.  Are the project I realized we don't do maintenance releases anymore, but we certainly did off of these old branches I assume you intend to remove. What am I missing?

**Comment by ruspl-afed** [comment]
I also do not understand why do we need to remove maintaince branches and define tags instead of them
Do we have any maintance cost for these branches to save any resources in the case of deletion, @vogella  @akurtakov ?
I know that many consumers of Eclipse Platform are tied to a specific release version for some reason. What might be the process of, say, fixing a CVE for some old released version if the branch was deleted.
1) branch by tag RX_0_maintenance_FINAL
2) push the fix
3) ... create the tag RX_0_maintenance_MUCH_MORE_FINAL?

**Comment by sravanlakkimsetti** [comment]
We should keep maintenance branches. These contains our history. 
-1 to remove maintenance branches.

**Comment by mickaelistria** [comment]
> In the past we have made releases off the maintenance branches. Deleting such a branch deletes the history that went into that release.

I don't think it's true. The history remain by fetching the *tag* for a given release.
There are some small benefits I see in removing older unsupported branches: listing the remote branches directly say what's still supported, less refs also means that the list becomes shorter and supported branches become then easier to find (in GitHub UI and via CLI).

**Comment by vogella** [comment]
> In the past we have made releases off the maintenance branches. Deleting such a branch deletes the history that went into that release. As a project I realized we don't do maintenance releases anymore, but we certainly did off of these old branches I assume you intend to remove. What am I missing?

Sorry, missed the question, but @mickaelistria asked corretly. A branch is just a pointer to a commit, see .git/refs/heads and check the content of the files.
