### ISSUE TITLE
Version 3.13.0 built against JDK 17 and throws java.lang.IllegalArgumentException: Unsupported class file major version 61

### ISSUE THREAD

**Issue by alex-korobko** [eclipse-platform/.github#131]
Guys, 

Since version 3.13.0 switched to JDK 17 any project that is still on JDK 11 or earlier that uses transitive dependencies throws an error `java.lang.IllegalArgumentException: Unsupported class file major version 61`
Maybe it would be better to increment the major version for such a change, like, starting with 4.*? 
Workarounds:
Users to define explicitly lib version [3.12.300](https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.text/3.12.300) as the latest which still on JDK 11

**Comment by merks** [comment]
No I don’t think that is better.  Pretty much all bundles switched the BREE to Java 17 for the 4.28 release and such BREE changes are not API breaking so do not require a major version increment.  That didn’t happen when the BREE was charged to Java 11 either.  And it can’t be unpublished from Maven in any case.
