### ISSUE TITLE
"The super interfaces set has been reduced"

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/.github#139]
With an today OOmphed platform workspace i see 19 weird errors:
"The super interfaces set has been reduced"
"The major version should be incremented in version 2.2.700, since API breakage occurred since version 2.2.700"

Which i don't understand

![image](https://github.com/eclipse-platform/.github/assets/51790620/90a45e7d-49af-4c53-a4a8-826b1644ee4a)

**Comment by iloveeclipse** [comment]
This sounds like a usual glitch in the matrix, that occurs often in PDE. I almost always see 300 API errors in SWT (and that since years).
Typically a rebuild or restart + clean build helps.

**Comment by merks** [comment]
Sometimes this is what I do, i.e., refresh the API baseline and then an Apply And Close forces a full build...

**Comment by jukzi** [comment]
totally fresh. "build...clean" did not solve it. nor a restart.

**Comment by jukzi** [comment]
refresh baseline made those errors disappear. - but now i see  all those swt errors @iloveeclipse mentioned :-(
![image](https://github.com/eclipse-platform/.github/assets/51790620/bff44ea8-dbe7-43a4-8dfd-c46437fa56f3)

**Comment by iloveeclipse** [comment]
1) Since I'm old school API tools user, I have manually set baseline to the local 4.28 SDK installation.
2) I don't see API errors on osgi bundles using latest nightly SDK build and the API baseline above.

**Comment by jukzi** [comment]
Deleting baseline deleted the markers. "Help/Perform Setup Tasks..." recreated baseline. a Project/Clean... recreated all the swt errors :-(

**Comment by merks** [comment]
At least it's consistent.   I don't currently have time to try to reproduce this problem.  But I have seen this before and then at some point it goes away and for me it's currently away in my older setup...

**Comment by merks** [comment]
It's not a great suggestion, but deleting the errors makes the go away for a while...

**Comment by iloveeclipse** [comment]
I wonder if reusing workspace affects API tools: `[WARNING] The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.`

**Comment by vogella** [comment]
Still an issue? Please reopen
