### ISSUE TITLE
Compiler warnings not shown

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/.github#144]
When creating a PR a jenkins jobs runs that checks for compiler warnings. But all of them are shown empty.
example:
https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-986/2/java/fileName.-320603757/source.26df7935-bc10-47b7-b2f9-be5c4e44dee4/#7

![image](https://github.com/eclipse-platform/.github/assets/51790620/fd25852e-5e6d-47ae-8dd3-fce2cb629802)

in the logfile https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-986/2/consoleText
one could find there is error message in the next liness. for example:

```
11:28:16.247 [WARNING] /home/jenkins/agent/workspace/eclipse.platform.ui_PR-986/tools/bundles/org.eclipse.e4.tools.emf.ui/src/org/eclipse/e4/tools/emf/ui/internal/common/properties/ProjectOSGiTranslationProvider.java:[7] 
	import java.security.AccessController;
	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The type AccessController has been deprecated since version 17 and marked for removal

```

The same effect is visible in the pull request which shows empty annotations:

![image](https://github.com/eclipse-platform/.github/assets/51790620/3f5f0487-62bb-4aa3-a6eb-cfa1ef0f1d78)

**Comment by Bananeweizen** [comment]
things to check would be:
* upgrade the warnings-ng plugin
* try the eclipse() tool instead of the java() tool
* check if any settings of the linux agents might lead to adding artificial linebreaks to the VNC console (I have no idea if something like that is possible)

**Comment by akurtakov** [comment]
Do you consider this one done?

**Comment by jukzi** [comment]
done.
