### ISSUE TITLE
@PostConstruct and @PreDestroy getting error even though i imported packages

### ISSUE THREAD

**Issue by raghu225599** [eclipse-platform/.github#163]
when iam using @PostConstruct and @PreDestroy annotations even though i imported the packages which are 
import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
getting error saying PostConstruct cannot be resolved to a type,same with PreDestroy also when using the eclipse IDE for Java and Web Developers 2020-06 version

**Comment by jonahgraham** [comment]
How have you added the javax.annotation package to your classpath?
