### ISSUE TITLE
An internal error occurred during: "Check Configuration"

### ISSUE THREAD

**Issue by NikunjChavda19** [eclipse-platform/.github#164]
###  **Summary**

While opening and using the eclipse it shows popup with error "An internal error occurred during: "Check Configuration"" 
please, refer attached images of error.

###  **Steps to reproduce**

- Updated/Installed new version of eclipse, while open eclipse throw popup  - this is very important
- Version: 2023-09 (4.29.0)
- Build id: 20230907-1323

###  **What is the current bug behavior?**

After closing popup i can continue with work but after some time again popup gets generate

###  **Relevant logs and/or screenshots!**

 ![image](https://github.com/eclipse-platform/.github/assets/149466667/eafa9cc9-c984-44b1-a2f7-103c42e19404)

 ![image](https://github.com/eclipse-platform/.github/assets/149466667/afe7b996-bc5c-4767-897b-251b1e059fbc)

###  **Priority**
[High]

@eclipse-platform-bot @eclipsewebmaster

**Comment by akurtakov** [comment]
This doesn't look like Platform project and would better be reported to https://github.com/eclipse-egit/egit for initial assessment.
