### ISSUE TITLE
Rework IDE Installation Process

### ISSUE THREAD

**Issue by IanDarwin** [eclipse-platform/.github#17]
The present installation process... compares poorly with the competition, shall we say.

- Downloading an installer just to download one of 4 or 5 pre-built install packages seems silly.
- The use of Zip and Tgz files is archaic. As a Unix greybeard I'm OK with that, but the world has largely moved on.- Both IntelliJ Idea and Android Studio can be installed with one click or one command (e.g., winget, the official Windows command-line installer).
- Java now includes jpackage which makes installers in non-interactive mode for all three major desktops (Windows on Windows, macOS on mac, Linux on Linux).

In an ideal world I would love to be able to install either "Eclipse for Java" or "Eclipse for Jakarta EE" with one click or one command (rpm, winget, click on link to dmg, etc).

Eclipse has been my favorite IDE for decades and I'd hate to see it losing market share because it is seen as being more involved to install than the competition.

I've used jpackage in my PDFshow and anyone is welcome to borrow from that installer (https://github.com/IanDarwin/pdfshow has my mkinstaller script).

**Comment by mickaelistria** [comment]
The Eclipse Installer comes from Eclipse Oomph project. Eclipse Platform itself doesn't use any installer. The Eclipse IDE and installer are downstream "packages" that are not controlled by Eclipse Platform project. So I suggest you bring this comment to some mailing-list like https://www.eclipse.org/lists/cross-project-issues-dev/ , https://www.eclipse.org/lists/ide-dev or https://www.eclipse.org/lists/eclipse-ide-wg/ .

**Comment by akurtakov** [comment]
For the record - there is https://flathub.org/apps/details/org.eclipse.Java which is single click install for Linux. It still has issues but IMHO this is the most promising "installer" for Linux.
