### ISSUE TITLE
How to set 'enable preview' for Java 22

### ISSUE THREAD

**Issue by MyhreAndersen** [eclipse-platform/.github#182]
Let's make sure issue is not already fixed in latest builds first.

- [ ] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

Goto: Properties -> Java Compiler -> JDK Compliance
Impossible to set level 22

I am using Eclipse 2024-3 ( Version: 2024-03 M2 (4.31.0 M2) ).

From a fresh installation and clean workspace:

* *<steps to...>*
* *<...setup environment>*

I tried

* *<steps to...>*
* *<... trigger issue>*

I expected: *<what was the expected outcome?>*

But got: *<what is the actual undesired behavior?>*

## Here is some relevant log output

From `<workspace>/.metadata/.log`
```
<relevant log output>
```

## Tested under this environment:
* OS & version: ...
* Eclipse IDE/Platform version (as shown in *Help > About*): Version: 2024-03 M2 (4.31.0 M2)
* ...Anything else that can be useful...

## Community

- [ ] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by mickaelistria** [comment]
This "eclipse-platform" org doesn't particularly deal with tracking development of the Java Development Tools. Can you please report this issue to https://github.com/eclipse-jdt/eclipse.jdt.ui/issues ?
