### ISSUE TITLE
Eclipse Installer: Do you trust unsigned content of unknown origin? Cancel exits install

### ISSUE THREAD

**Issue by minfrin** [eclipse-platform/.github#183]
Let's make sure issue is not already fixed in latest builds first.

- [ ] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace:

Run the Eclipse installer, attempt to install CDT, DataTools and JDT. Latest version 2024-03.

I expected: Successful installation.

But got: "Do you trust unsigned content of unknown origin". No we don't. Only option is to exit install.

## Here is some relevant log output

![](https://gitlab.eclipse.org/eclipsefdn/helpdesk/uploads/1b056b89ca0e741c080944095d098846/image.png)

![](https://gitlab.eclipse.org/eclipsefdn/helpdesk/uploads/8b3dab0c2f4b53739f08f9a08629e0e3/image.png)

## Tested under this environment:
* OS & version: MacOS 13.6.3
* Eclipse IDE/Platform version (as shown in *Help > About*): Installer version: 1.31.0 Build 329

## Community

- [X] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by akurtakov** [comment]
Installer lives in another project (https://github.com/eclipse-oomph/oomph ) ships products built by yet another project (https://github.com/eclipse-packaging/packages) and what you see is that package you installed is including Marketplace client plugin which itself includes the bundles in question (https://github.com/eclipse-mpc/epp.mpc/blob/master/org.eclipse.epp.mpc.feature/feature.xml#L25). Nothing of that happens in eclipse-platform project nor the project can change anything thus I'm closing this one. 
IMHO it's best to report at https://github.com/eclipse-packaging/packages . @merks / @jonahgraham  - maybe you would like to help with this report entering the proper place and be handled accordingly.

**Comment by jonahgraham** [comment]
I'm not sure where this belongs - the bundles in question are jar signed, so it looks like it could even be p2 causing the issue. @merks any ideas?

**Comment by merks** [comment]
There's also this issue:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4264
