### ISSUE TITLE
eclipse crashes with webkit2gtk4.0 version 2.44.0

### ISSUE THREAD

**Issue by markus-oehme-pg40** [eclipse-platform/.github#197]
Let's make sure issue is not already fixed in latest builds first.

- [ ] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace:

* open Eclipse Marketplace
* Eclipse freezes and crashes after 10 seconds

I tried

* downgrading to version 2.42.5 fixes the problem

I expected: a working program

But got: a crashed program

## Here is some relevant log output

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f62883b6260, pid=36222, tid=36223
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.9+9 (17.0.9+9) (build 17.0.9+9)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (17.0.9+9, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libwebkit2gtk-4.0.so.37+0xdb6260]
```

## Tested under this environment:
* OS & version: Fedora 39 on amd64
* Eclipse IDE/Platform version (as shown in *Help > About*): 2023-12 (4.30.0)  installed from https://copr.fedorainfracloud.org/coprs/dusansimic/eclipse/; the same problem occurred with the flathub package (versions 2023-12 and 2024-03)

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by akurtakov** [comment]
Please try the latest I-build as asked in the template as this one is most likely duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/1108 .

**Comment by markus-oehme-pg40** [comment]
I searched hard for https://github.com/eclipse-platform/eclipse.platform.swt/issues/1108  but did not find it. :/  That could have saved me a lot of time ...
It is indeed fixed in the newest build.
