### ISSUE TITLE
Following the CONTRIBUTING.md does not succeed succesfully

### ISSUE THREAD

**Issue by tivervac** [eclipse-platform/.github#199]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace:

* Run the Oomph setup [mentioned](https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#creating-an-eclipse-development-environment) in the `CONTRIBUTING.md`. 
* Wait for it to finish
* Run the `Runtime Workspace` launch profile

I expected: A clean Eclipse to launch

But got: A stacktrace, see below

## Here is some relevant log output

From `<workspace>/.metadata/.log`
```
WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
OpenJDK 64-Bit Server VM warning: You have loaded library /home/t21/platform-sdk/git/eclipse.platform.swt/binaries/org.eclipse.swt.gtk.linux.x86_64/libswt-gtk-4965r6.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
!SESSION 2024-04-22 17:23:53.934 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.9
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.sdk.ide
Command-line arguments:  -product org.eclipse.sdk.ide -data /home/t21/platform-sdk/ws/../runtime-workspace -dev file:/home/t21/platform-sdk/ws/.metadata/.plugins/org.eclipse.pde.core/Runtime Workspace/dev.properties -os linux -ws gtk -arch x86_64 -consoleLog

!ENTRY org.eclipse.osgi 4 0 2024-04-22 17:23:54.794
!MESSAGE Application error
!STACK 1
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	/home/t21/platform-sdk/git/eclipse.platform.swt/binaries/org.eclipse.swt.gtk.linux.x86_64/libswt-gtk-4965r6.so: /home/t21/platform-sdk/git/eclipse.platform.swt/binaries/org.eclipse.swt.gtk.linux.x86_64/libswt-gtk-4965r6.so: invalid ELF header
	no swt-gtk in java.library.path: /usr/lib64/firefox:/usr/lib64/firefox/plugins:/usr/lib64/firefox:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	no swt in java.library.path: /usr/lib64/firefox:/usr/lib64/firefox/plugins:/usr/lib64/firefox:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	/home/t21/.swt/lib/linux/x86_64/libswt-gtk-4965r6.so: /home/t21/.swt/lib/linux/x86_64/libswt-gtk-4965r6.so: invalid ELF header
	Can't load library: /home/t21/.swt/lib/linux/x86_64/libswt-gtk.so
	Can't load library: /home/t21/.swt/lib/linux/x86_64/libswt.so
	/home/t21/.swt/lib/linux/x86_64/libswt-gtk-4965r6.so: /home/t21/.swt/lib/linux/x86_64/libswt-gtk-4965r6.so: invalid ELF header

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:345)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:254)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:209)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:155)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:170)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:721)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:185)
	at org.eclipse.ui.internal.ide.application.IDEApplication.createDisplay(IDEApplication.java:182)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:125)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:679)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:616)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1492)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1465)
An error has occurred. See the log file
/home/t21/platform-sdk/runtime-workspace/.metadata/.log.
```

## Tested under this environment:
* OS & version: Fedora 39
* Eclipse IDE/Platform version (as shown in *Help > About*): master between 2024-06 M1 and M2

## Fix

I figured out through this [ticket](https://github.com/eclipse-platform/eclipse.platform.swt/issues/1163) that one of the libraries wasn't correctly cloned because I didn't have `git lfs` installed.

A `sudo yum install git-lfs` and a `cd platform-sdk/git/eclipse.platform.swt; rm -rf binaries; git reset --hard origin/master` fixed it.

I'm unsure how we best solve this. Ideally this would be done in Oomph, but I suppose Oomph can't just install git-lfs. The second best choice would be for Oomph to fail and tell me that I need to enable git lfs. The least convenient, but easiest to implement solution, would be to just add the git-lfs requirement in the `CONTRIBUTING.md`.

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by merks** [comment]
This sounds familiar but also like something @HannesWell has already addressed in oomph by ensuring that egit/jgit lfs support is installed and the appropriate preferences are set.

**Comment by merks** [comment]
This commit history suggests the changes to support this should already be in place

https://github.com/eclipse-platform/eclipse.platform.swt/commits/master/bundles/org.eclipse.swt.tools/Oomph/platformSwt.setup

I can try it myself tomorrow.

**Comment by tivervac** [comment]
Hmm I didn't have the `Enable LFS support globally` option in Eclipse enabled, but I also didn't have git-lfs installed at all

**Comment by merks** [comment]
It's really strange because that preference is set and the bundle is installed here by the parent project of SWT's setup:

![image](https://github.com/eclipse-platform/.github/assets/208716/91b7b889-5677-4aee-92ed-4ff6fd79c15d)

And in the performer I can see those tasks:

![image](https://github.com/eclipse-platform/.github/assets/208716/3f978dca-8f51-4a06-bfca-a60cc00e84a5)

**Comment by merks** [comment]
If I create an IDE just for SWT, then I see LFS is installed:

![image](https://github.com/eclipse-platform/.github/assets/208716/88630613-779b-485b-9e69-d9eedaa7bc9a)

I think the preference is set:

![image](https://github.com/eclipse-platform/.github/assets/208716/3e68dd1f-6b32-44a8-a898-6127d4ea2a04)

And I can create a runtime workbench that is definitely using the SWT from the workspace:

![image](https://github.com/eclipse-platform/.github/assets/208716/8c56d7fa-a152-4d96-98f2-16ba16756da7)

I don't have a good theory for why you would see something different...

**Comment by tivervac** [comment]
I'm on a different computer today, and I tried the same. Same environment (no LFS installed), same error messages, same fix

**Comment by merks** [comment]
Indeed, I would expect installing org.eclipse.jgit.lfs would allow the clone task in the IDE to do anything related to LFS support even with no native git installed.

@tivervac 

If you do Help -> Perform Setup Tasks and select the p2 director, is org.eclipse.jgit.lfs in the list?

![image](https://github.com/eclipse-platform/.github/assets/208716/bd8f7f7c-e4de-4519-bf20-24f955fa6c88)

I assume it must be present...

I wonder if it's possible that some global git configuration is causing some unintended/unexpected interaction?

**Comment by tivervac** [comment]
@merks Seems to be present indeed

![image](https://github.com/eclipse-platform/.github/assets/3389524/ff9b98e8-54a3-431a-ab55-3cfd6ee978e6)

My global .gitconfig looks like below. I don't see any issues with that. The git hook shouldn't be in the way either.

```
[color]
  ui = true
[core]
  editor = vim
  hooksPath = ~/.config/git/hooks/
[diff]
  tool = vscode
[alias]
  unstage = reset HEAD --
  pushf = push --force-with-lease
  mergeff = merge --ff-only
  l   = log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
  c   = commit
  p   = push
  rekt = status
  s   = status
  d   = diff
  a   = add -A
  ch  = checkout
  b   = branch
  rpr = remote prune origin
  f   = fetch --all
  rom = rebase origin/master
  lom = l origin/master
  cp  = cherry-pick
[credential]
  helper = cache --timeout=3600
[push]
  default = current
[gui]
	spellingdictionary = none
	commitmsgwidth = 72
[protocol]
	version = 2
[gpg]
	program = gpg2
[pull]
	rebase = true
```

**Comment by merks** [comment]
@tivervac 

If JGit LFS is installed then this preference page should have the button enabled:

![image](https://github.com/eclipse-platform/.github/assets/208716/06a27fd5-e42a-4366-845d-6684c70777d1)

And the setup should have set the following preference to be check marked.

![image](https://github.com/eclipse-platform/.github/assets/208716/09080b55-2bb9-4da7-8891-6e4f0560cdba)

With those in place, clones should just use LFS support.

@tomaswolf 

Is there something in @tivervac settings that might cause the IDE to use natively installed git "things" such that JGit's LFS support is not being used as expected?

**Comment by tivervac** [comment]
The button is visible and the checkmark is enabled

**Comment by merks** [comment]
So everything appears to be installed and configured appropriately which leave the mystery of why cloning does materialize the LFS content.  Even a manually created new clone should "just work" in this installation, but I assume that if you manually create another clone of SWT, that also doesn't work properly...

**Comment by tomaswolf** [comment]
I don't know what might be the problem. But the built-in LFS support in JGit has [issues](https://bugs.eclipse.org/bugs/buglist.cgi?bug_status=NEW&order=changeddate%20DESC%2Cpriority%2Cbug_severity&product=EGit&product=JGit&query_format=advanced&resolution=---&short_desc=lfs&short_desc_type=allwordssubstr). Possibly one of these causes trouble in tivervac's setup.

**Comment by merks** [comment]
I wonder what that button does.  I've never pushed it...

**Comment by merks** [comment]
I'm not sure these is actionable left here?  😢

**Comment by tivervac** [comment]
Sadly, I don't think so either. I tried reoomphing a final time and now it simply works.
