### ISSUE TITLE
First Impressions

### ISSUE THREAD

**Issue by merks** [eclipse-platform/.github#2]
If you look at our new organization page, what's your first impression?

https://github.com/eclipse-platform/

Cool slash screen?!

But then you see this:

![image](https://user-images.githubusercontent.com/208716/163329666-cb6a4577-1744-4a7f-b777-2ae942e70f53.png)

And, at least for me, I think wow, how retro is that?

Maybe it would be better if we showed something that appears more modern, and maybe even something that demonstrates theming, like this:

![image](https://user-images.githubusercontent.com/208716/163329507-4508f5aa-76b0-4f9a-aaab-f35a3831c469.png)

What do you think?

**Comment by laeubi** [comment]
Honestly I would simply remove the screenshot at all and link to the download packages (and probably other sites where one can get eclipse based projects) as one screenshot can't really express much. Beside that, I don't think that the "dark theme" looks much more modern...

**Comment by mickaelistria** [comment]
The image is taken fron help content. It'd be nice to upgrade it in help and this .github would be improved without change

**Comment by merks** [comment]
It would indeed be nice, but it's a huge task to fix all the following imagines (and probably many, many more others):

https://github.com/eclipse-platform/eclipse.platform.common/tree/master/bundles/org.eclipse.platform.doc.isv/guide/images/

I'm not sure anyone plans to do that...

So, failing that daunting task, what should we do?

**Comment by vogella** [comment]
I can update the image in the help. Searching now for it.

**Comment by vogella** [comment]
> It would indeed be nice, but it's a huge task to fix all the following imagines (and probably many, many more others):
> 
> https://github.com/eclipse-platform/eclipse.platform.common/tree/master/bundles/org.eclipse.platform.doc.isv/guide/images/
> 
> I'm not sure anyone plans to do that...

Matthias Becker from SAP did a huge update of these images already and AFAIK is still interested in this topic. So in case you see outdated screenshots, please open an issue an cc him

**Comment by vogella** [comment]
Screenshot updated, closing

**Comment by merks** [comment]
This scares me.  Did you look at how this looks in the documentation?  All the images will be like the one on this page, except for one dark theme image that doesn't show project content like in all other images?

https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fint_eclipse.htm&cp%3D2_0_0_2

I think it's more import that the documentation remain cohesive than that we reuse an image from it on the organization page.  :-(

**Comment by merks** [comment]
@vogella 

I would really **strongly** suggest you revert your inappropriate change to the documentation.

**Comment by vogella** [comment]
> @vogella
> 
> I would really **strongly** suggest you revert your inappropriate change to the documentation.

Lets see if I can improve it. Most the starter screenshots look outdated.

**Comment by merks** [comment]
Yes, it's totally outdated, but if they're going to be updated, they should show the same content as before and be a consistent set of images across that set of documentation.   I don't think it's an important goal here to share the image from the documentation.  Your image looks bad, e.g., the overflow of the toolbar button in the upper left view...

Why does the sharing even matter when, you can just paste an image and there will be a link, e.g.,

https://user-images.githubusercontent.com/208716/163329507-4508f5aa-76b0-4f9a-aaab-f35a3831c469.png

I assume that link must be permanent.  Or not?  

Why is sharing important?

**Comment by vogella** [comment]
@merks like I said, I'm improving the change at the moment ...

**Comment by vogella** [comment]
https://github.com/eclipse-platform/eclipse.platform.common/pull/5/files

**Comment by merks** [comment]
That looks better now!  It would have been even better if the toolbar didn't overflow onto a new line:

![image](https://user-images.githubusercontent.com/208716/163363703-d6b85a10-c6f3-4d3a-a844-d3bef7674f8f.png)

Thanks.

**Comment by rolfth** [comment]
My browser has 'advanced tracking protection' on by default. This hides these images all together:
![image](https://user-images.githubusercontent.com/420839/163372072-a37dee70-01c5-4e89-8061-4d10442d7b5f.png)

**Comment by vogella** [comment]
> That looks better now! It would have been even better if the toolbar didn't overflow onto a new line:
> Thanks.
Done with https://github.com/eclipse-platform/eclipse.platform.common/pull/8
