### ISSUE TITLE
An internal error occurred during: "DSF Source Lookup"

### ISSUE THREAD

**Issue by BenthamSoftwareServices** [eclipse-platform/.github#209]
Message windows appears = An internal error occurred during: "DSF Source Lookup"

Error occurs when Launching any ESP-IDF project in Debug mode.

Eclipse IDE for Embedded C/C++ Developers (includes Incubating components)
Version: 2024-03 (4.31.0)
Build id: 20240307-1437
OS: Windows 11, v.10.0, x86_64 / win32
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.11+9
Java version: 17.0.11

Using ESP-IDF v5.2.1

[error.log](https://github.com/eclipse-platform/.github/files/15380291/error.log)

OKing the error message Window closes it and appears to have no effect on normal debugging operation.  I would like to fix the source of the error, or, if that is not possible, supress it.

- [x ] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by merks** [comment]
It looks like org.eclipse.cdt.lsp.LspUtils.isFileOpenedInLspEditor(LspUtils.java:96) is doing work that can only be done on the main/UI thread.   Please open an issue here:

https://github.com/eclipse-cdt/cdt-lsp/issues

Issues can't be moved between organizations so I will close this one.
