### ISSUE TITLE
Installation doesn't work: Unable to create resource URLImageDescriptor

### ISSUE THREAD

**Issue by igornem1** [eclipse-platform/.github#216]
Let's make sure issue is not already fixed in latest builds first.

- [ x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

Version: 2024-06 (4.32.0)
Build id: 20240606-1231

## Steps to reproduce

* *Download package https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2024-06/R/eclipse-java-2024-06-R-linux-gtk-x86_64.tar.gz*
* *Unzip it*
* *Run /eclipse*
OR
* *Download Eclipse installer https://www.eclipse.org/downloads/download.php?file=/oomph/epp/2024-06/R/eclipse-inst-jre-linux64.tar.gz*
* *Unzip it*
* *Run /eclipse-inst*
* *Selected [Eclipse IDE for Enterprise Java and Web Developers]*
* *Run installation*
* *Run /eclipse*

I tried

* *Run /eclipse*

I expected: *Regular Eclipse window*

But got: *Eclipse window with many errors(see screenshot)*
![image](https://github.com/eclipse-platform/.github/assets/12052605/26744657-7caa-49d3-ab2c-82ea351f0ed4)

## Attached log exported from Eclipse Workspace log tab

[eclipse.log](https://github.com/user-attachments/files/15969335/eclipse.log)

## Tested under this environment:
* OS & version: Linux Mint 21.3    
* Eclipse IDE/Platform version (as shown in *Help > About*): 
Version: 2024-06 (4.32.0)
Build id: 20240606-1231

## Community

- [X] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by merks** [comment]
FYI @nitind 

This problem should be reported here and I can't move this issue to a different GitHub organization

https://github.com/eclipse-packaging/packages/issues

Note that that this works fine for me on Windows:

![image](https://github.com/eclipse-platform/.github/assets/208716/b671af27-9e25-4961-8a85-3b57ef60bb2b)

Are you, or have you tried, opening the IDE with a fresh empty new workspace?
