### ISSUE TITLE
Unable to read Repository Issue

### ISSUE THREAD

**Issue by keerthibattana** [eclipse-platform/.github#218]
## Steps to reproduce

I have installed the Eclipse SDK 4.2.1 Juno

* *<steps to...>*
* *<...setup environment>*

I tried Installing the "ADT Tools using the URL "http://tools.hana.ondemand.com/latest", which is ending up in the error "Unable to read repository in the http://tools.hana.ondemand.com/latest"

* *<steps to...>*
* *<... trigger issue>*

I expected: *The ADT Toolds to be downloaded in order for me to work on the CDS Views*

But got: *Unable to read repository in the http://tools.hana.ondemand.com/latest*

## Here is some relevant log output

Unable to connect to repository http://tools.hana.ondemand.com/latest/content.xml
Unable to connect to repository http://tools.hana.ondemand.com/latest/content.xml
Connection refused: connect
```

## Tested under this environment:
* Eclipse IDE/Platform version (as shown in *Help > About*): ... Eclipse SDK 4.2.1(Juno)


## Community

- []
![MicrosoftTeams-image](https://github.com/user-attachments/assets/b4d2294f-90ba-4667-8e39-ab9248036c2f)
 I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by HeikoKlare** [comment]
The issue does not seem to be related to the Eclipse platform itself but to an SAP tooling update site, so you should probably contact SAP support for getting help.
Just as a note: You refer to Eclipse Juno, which has been released in 2012. I am not sure whether it will be possible to use artifacts from a "latest" update site with a 12-year-old Eclipse release. At least the SAP update site states that it provides the ADT Tools "for the latest Eclipse version."

**Comment by merks** [comment]
Probably the host is redirecting to https and that ancient version of eclipse handles that poorly.  Perhaps try using an https url directly.
