### ISSUE TITLE
Simplify api removal process

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/.github#22]
The current process for marking API for removal is relatively complex. 
We already general a list of elements which are marked for removal with the @Deprecate(forRemoval=true) flag.

I suggest to make this sufficient for remove API after the API freeze period.

@tjwatson @akurtakov WDYT?

**Comment by mickaelistria** [comment]
Can you please elaborate on which particular parts you think are complex?

**Comment by tjwatson** [comment]
> Can you please elaborate on which particular parts you think are complex?

Was about to ask the exact same question.  Not sure what parts you are thinking of dropping.

**Comment by vogella** [comment]
I think we could drop most of the steps from  here: https://wiki.eclipse.org/Eclipse/API_Central/API_Removal_Process

**Comment by vogella** [comment]
Especially manually updating the porting guide https://git.eclipse.org/c/platform/eclipse.platform.common.git/tree/bundles/org.eclipse.platform.doc.isv/porting/removals.html

**Comment by mickaelistria** [comment]
> Especially manually updating the porting guide https://git.eclipse.org/c/platform/eclipse.platform.common.git/tree/bundles/org.eclipse.platform.doc.isv/porting/removals.html

OK.
I think what matters more than the removal is the `deprecation(forRemoval=true)`. This is probably what we should mention in this guide so people react immediarly. The good news is that it *should* be possible to list of the types/fields/methods which have this annotation. So if one can build a query listing all the deprecated for removal stuff, we may consider replacing the manual edit by a link to the query results.
However, I don't think it's actually less work than doing manual updates.

**Comment by vogella** [comment]
In short we want to rely on http://help.eclipse.org/latest/topic/org.eclipse.platform.doc.isv/reference/api/deprecated-list.html#forRemoval

**Comment by vogella** [comment]
See PMC meeting minutes for the simplification https://github.com/eclipse-platform/.github/wiki/PMC-Meeting-minutes
