### ISSUE TITLE
ECF: Compiling for Java version '1.5' is no longer supported.

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/.github#220]
Hello again. Trying to setup a platform workspace from scratch with OOmph as described in https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md results in a workspace with many compilation errors. The root cause seems to be

```
Compiling for Java version '1.5' is no longer supported. Minimal supported version is '1.8'	BaseID.java	/org.eclipse.ecf.identity/src/org/eclipse/ecf/core/identity	line 0	Java Problem
```
![image](https://github.com/user-attachments/assets/529e097e-4ef3-4e3b-90ee-513d8072eaa1)

It seems that even JDT can not compile itself anymore
`Compiling for Java version '1.2' is no longer supported. Minimal supported version is '1.8'	List.java	/converterJclMin/src/java/awt	line 0	Java Problem
`
![image](https://github.com/user-attachments/assets/6d8965ed-34f3-4217-a42d-169e3ff72afd)

**Comment by jukzi** [comment]
probably related to https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2761

**Comment by merks** [comment]
Have you done a pull on the ecf clone?

**Comment by merks** [comment]
Sorry wrong concern 🙁. Is everything pulled?  I’ve not seen this and keep my sdk ide up to date.

**Comment by merks** [comment]
I go you meant the subject prefix to be ecj not ecf. 

Note that this appears to be project content problems not setup problems so be sure you have the latest content. I can't check until late in the day.

**Comment by jukzi** [comment]
@merks I did clone everything from scratch. So ECF is up to date. As far as i understand ECJ does not compile projects anymore that try to compile for 1.5 but ECF still configured to compile for 1.5 - see https://github.com/search?q=repo%3Aeclipse%2Fecf%20org.eclipse.jdt.core.compiler.compliance%3D1.5&type=code
@iloveeclipse what is the plan for (almost unmaintained) projects that still build for old java versions?

**Comment by merks** [comment]
If this missed something 

https://github.com/eclipse/ecf/pull/121/files

It would be best to open an ECF issue or pr for it.
