### ISSUE TITLE
FEDORA: After update to version 4.33 Eclipse wont starts. !MESSAGE FrameworkEvent ERROR

### ISSUE THREAD

**Issue by rpdap** [eclipse-platform/.github#225]
FEDORA: After automatic update to Eclipse 4.33 
Eclipse won't start. !MESSAGE FrameworkEvent ERROR in log file.
Fedora provided has Eclipse 4.33 in the software, but only Java 21.0.4 is available on Fedora.

**Comment by mickaelistria** [comment]
The issue is specific to Fedora package and needs to be reported to the provider of the Eclipse Fedora package. The Eclipse Fedora package is not maintained/supported by the Eclipse Platform project.

**Comment by mickaelistria** [comment]
FWIW, you can use Eclipse IDE in Fedora without using the package. Just having Java installed and downloading/expanding the archive is usually working well. You can also try to use Flatpak to get Eclipse IDE https://flathub.org/apps/org.eclipse.Java , but this setup has some limitations too.
