### ISSUE TITLE
Updating to 2024-09-R breaks build configuration / indexer / lookup of compile-commands.json

### ISSUE THREAD

**Issue by ronso0** [eclipse-platform/.github#227]
**I'm aware this issue is probably hard / tedious to reproduce** and that cmake4eclipse (or rather some conflict/incompatibility) might be the culprit, so my main question is actually:
**what do I need to backup when testing a new Eclipse version** for being able to go back to a working configuration?
which global config files are responsible for all the affected build configuration mentioned below?

## Steps to reproduce

* have a project / workspace created with Eclipse CDT 2024-03-R with **cmake4eclipse** plugin that can be build with both Eclipse and cmake manually, indexer works, compile-commands.json is found in configured build directory
* upgrade to 2024-09-R
* (clone an existing, working workspace directory)
* start Eclipse, select the cloned workspace
* accept dialog that warns about workspace of an older version, will be upgraded, may be incompatible etc.
* open any code file

## Expected
* all symbols and includes are resolved

## What happens
* nothing is resolved
* tried to rebuild the index:
log shows this warning
```
!ENTRY org.eclipse.cdt.managedbuilder.core 4 0 2024-10-07 09:51:24.362
!MESSAGE Compilation database (usually compile_commands.json) path not set.
!STACK 1
org.eclipse.core.runtime.CoreException: Compilation database (usually compile_commands.json) path not set.
	at org.eclipse.cdt.managedbuilder.internal.language.settings.providers.CompilationDatabaseParser.processCompileCommandsFile(CompilationDatabaseParser.java:284)
	at org.eclipse.cdt.managedbuilder.internal.language.settings.providers.CompilationDatabaseParser$1.runInWorkspace(CompilationDatabaseParser.java:440)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
!SUBENTRY 1 org.eclipse.cdt.managedbuilder.core 4 0 2024-10-07 09:51:24.363
!MESSAGE Compilation database (usually compile_commands.json) path not set.
```
* try to build 'Active configuration':
   > Errors occurred during the build.
Errors running builder 'CDT Builder' on project 'mixxx'.
Cannot invoke "java.net.URI.getScheme()" because "uri" is null

## Okay, nothing to worry about, I backed up my workspace, right?
I switched back to 2024-03-R and work with the original workspace.
Outcome is the same as above. Can't rebuild the index, can't build from within Eclipse.

## I also noticed that
(back in 2024-03-R with the old, untouched workspace) in Project --> C/C++ Build the _Build location_ is now (${workspace_loc:/ _project name_ }/ and clicking on _Workspace_ in order to select a directory would not list my actual build directory, only a directory I have been using ages ago.
Copying my build dir to the expected location and picking that as _Build location_ does not help.

## Tested under this environment:
* Ubuntu Studio 20.04.5
* old version: Eclipse 2024-03 (4.31.0) -- Build id: 20240307-1437
* new version: 2024-09 (4.33.0) -- Build id: 20240905-0614

**Comment by merks** [comment]
Personally I generally create new IDE with each release.  

I'm not sure what "cloning a workspace" means, but you can't just generally copy a workspace folder to a different location because goodness knows what absolute paths are all stored under the .metadata folder that will be broken if you move/copy it.

Did you know you can roll back to an older installation state?

![image](https://github.com/user-attachments/assets/eca30a17-30b8-49d7-9f26-c9b89c1b3554)

There's really nothing the platform can do to fix CDT incompatibilities.  CDT-specific problems should be reported here:

https://github.com/eclipse-cdt/

**Comment by ronso0** [comment]
Oh sorry, my bad, this was the wrong repo.
Will head over to CDT then, thanks for the pointer!

**Comment by Bananeweizen** [comment]
The app for rolling back installation history is Eclipse itself. :) Help > About > Installation History.

**Comment by ronso0** [comment]
Well, **that** is some hidden feature!
