### ISSUE TITLE
an internal error occured during: Items filtering when creating Calculation view in Hana modeller

### ISSUE THREAD

**Issue by Padawan8** [eclipse-platform/.github#230]
Let's make sure issue is not already fixed in latest builds first.

- [ ] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace: 

We are facing the error message below with Eclipse for Committers 2024-06, in the Hana modeler perspective when creating a Calculated View.
![image(2)](https://github.com/user-attachments/assets/5f29959d-9ad1-4a77-8bef-e9959b570489)
![image(3)](https://github.com/user-attachments/assets/491db074-a75f-48c0-b25d-65525f8eb377)
We cannot test with 2024-09(faced another bug linked to SWT) or 2024-12(no hana perspective yet)

* *<steps to...>*
* *<...setup environment>*

I tried

* *<steps to...>*
* *<... trigger issue>*

I expected: *<what was the expected outcome?>*

But got: *<what is the actual undesired behavior?>*

## Here is some relevant log output

From `<workspace>/.metadata/.log`
```
<relevant log output>
```

## Tested under this environment:
* OS & version: ...
* Eclipse IDE/Platform version (as shown in *Help > About*): ...
* ...Anything else that can be useful...

## Community

- [ ] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by akurtakov** [comment]
I strongly recommend reporting to the Hana tool provider as reports that are not verified happening against latest eclipse are unlikely to be looked at at all.

**Comment by merks** [comment]
Indeed.  If the Hana folks determine this to be an Eclipse bug, they can open a bug with proper details of how we can reproduce the problem purely in Eclipse.  This bug report provides no stack traces and no ability to reproduce the described problem so this report is not actionable.

**Comment by Padawan8** [comment]
Hello all,Thank you for your feedback.How can I report it to the Hana tool team?Does it means reporting it to SAP directly?Regards,TheoSent from my iPhoneOn 30 Dec 2024, at 14:30, Ed Merks ***@***.***> wrote:﻿
Indeed.  If the Hana folks determine this to be an Eclipse bug, they can open a bug with proper details of how we can reproduce the problem purely in Eclipse.  This bug report provides no stack traces and no ability to reproduce the described problem so this report is not actionable.

**Comment by jukzi** [comment]
> Hello all,Thank you for your feedback.How can I report it to the Hana tool team?

@sratz can you comment on that?

**Comment by sratz** [comment]
> How can I report it to the Hana tool team?Does it means reporting it to SAP directly?

Yes, please open a ticket with SAP on component HAN-STD-DEV-MOD.
