### ISSUE TITLE
Allow the simrel to build without b3 technology

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/.github#24]
In https://github.com/eclipse/gef-classic/issues/70 we discused that simrel does not use the "regular" technologies other Eclipse projects like platform or EMF are using for their release process. This isssue could be used to list the missing requirements to move simrel of B3, which is currently know by only a few people. This hopefully could result in a workflow more people would know and hence able to maintain.

Tech which I think could be used:

- [ ] category.xml to define the structure of the simrel
- [ ] one or multiple target platforms to define the available software sides and the used version (if necessary) to go into the update site
- [ ] Tycho to build the update site (basically only aggregating the elements from the target platform based on the category structure
- [ ] Jenkin or GH action (if / once moved to Github) to validate any contributions

@merks or @jonahgraham could you start listing the missing features?  I would assume structure (category) does not change all the time, so projects would only have to update their target file.

**Comment by jonahgraham** [comment]
This is the thread from the last time we went down this path - https://www.eclipse.org/lists/cross-project-issues-dev/msg17982.html

**Comment by mickaelistria** [comment]
Platform is not the best place to track this. Please open dedicated issues to dedicated projects (PDE, Tycho, SimRel...).
