### ISSUE TITLE
Component version error, "No remedy found"

### ISSUE THREAD

**Issue by TheRealAyCe** [eclipse-platform/.github#25]
After the 2022-06 update a dialog pops up that shows some kind of conflict between two packages or package version.

This text shows below it.
```
Cannot complete the install because of a conflicting dependency.
  Software being installed: Git integration for Eclipse 6.2.0.202206071550-r (org.eclipse.egit.feature.group 6.2.0.202206071550-r)
  Software currently installed: Git integration for Eclipse - Task focused interface 6.1.0.202203080745-r (org.eclipse.egit.mylyn.feature.group 6.1.0.202203080745-r)
  Only one of the following can be installed at once: 
    Git integration for Eclipse - UI 6.0.0.202111291000-r (org.eclipse.egit.ui 6.0.0.202111291000-r)
    Git integration for Eclipse - UI 6.1.0.202203080745-r (org.eclipse.egit.ui 6.1.0.202203080745-r)
    Git integration for Eclipse - UI 4.8.0.201706111038-r (org.eclipse.egit.ui 4.8.0.201706111038-r)
    Git integration for Eclipse - UI 5.13.0.202109080827-r (org.eclipse.egit.ui 5.13.0.202109080827-r)
    Git integration for Eclipse - UI 4.9.2.201712150930-r (org.eclipse.egit.ui 4.9.2.201712150930-r)
    Git integration for Eclipse - UI 5.0.0.201806131550-r (org.eclipse.egit.ui 5.0.0.201806131550-r)
    Git integration for Eclipse - UI 5.6.0.201912101111-r (org.eclipse.egit.ui 5.6.0.201912101111-r)
    Git integration for Eclipse - UI 6.2.0.202206071550-r (org.eclipse.egit.ui 6.2.0.202206071550-r)
    Git integration for Eclipse - UI 5.2.0.201812061821-r (org.eclipse.egit.ui 5.2.0.201812061821-r)
  Cannot satisfy dependency:
    From: Git integration for Eclipse 6.2.0.202206071550-r (org.eclipse.egit.feature.group 6.2.0.202206071550-r)
    To: org.eclipse.equinox.p2.iu; org.eclipse.egit.ui [6.2.0.202206071550-r,6.2.0.202206071550-r]
  Cannot satisfy dependency:
    From: Git integration for Eclipse - Task focused interface 6.1.0.202203080745-r (org.eclipse.egit.mylyn.feature.group 6.1.0.202203080745-r)
    To: org.eclipse.equinox.p2.iu; org.eclipse.egit.mylyn.ui [6.1.0.202203080745-r,6.1.0.202203080745-r]
  Cannot satisfy dependency:
    From: EGit Mylyn UI 6.1.0.202203080745-r (org.eclipse.egit.mylyn.ui 6.1.0.202203080745-r)
    To: java.package; org.eclipse.egit.ui [6.1.0,6.2.0)
```

I have no idea how to solve that. I deleted many old update site entries that for some reason Eclipse had collected over the years.

When I close it it shows "Searching alternate solutions..." and takes an extremely long time for any progress to be made.

Finally it shows this:
![eclipseerror](https://user-images.githubusercontent.com/11407231/174431552-3df93d42-94f7-47ad-a571-0633eb09bb73.png)

I wasn't sure where to report this. I used to report bugs on the Eclipse bugtracker but it seems to have been replaced by GitHub.

**Comment by akurtakov** [comment]
This is Egit bug and AFAIK EGit project still uses bugzilla to track issues.  Please open your bug at https://bugs.eclipse.org/bugs/enter_bug.cgi?product=EGit . 
IMHO the fix is to uninstall "Git integration for Eclipse - Task focused interface" as it's dependency "Mylyn" has been removed from simultaneous release via https://git.eclipse.org/c/simrel/org.eclipse.simrel.build.git/diff/egit.aggrcon?id=fadb9deb14c86da37d2b0b29026f7faf9201ba09

**Comment by Bananeweizen** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=562482 and especially https://git.eclipse.org/r/c/egit/egit/+/194240.

**Comment by TheRealAyCe** [comment]
I uninstalled "Git integration for Eclipse - Task focused interface" and "Java implementation of Git". Everything seems to work now. Thanks!

For someone less knowledgable about the whole Eclipse system the dialog is a bit annoying, confusing and scary though, as the "auto-resolving" of that issue takes a long time in which you cannot use Eclipse, and of course you wouldn't want to accidentally uninstall a big module that you still need.
