### ISSUE TITLE
[Usability] Make it easier to simply upgrade Eclipse to the latest version

### ISSUE THREAD

**Issue by jubax** [eclipse-platform/.github#33]
Every time a new major Eclipse version comes out I wish I could just have a button "check for updates" which will me show this next major version (e.g. when I'm on 2022-03 then I want to see both updates for 2022-03 and also 2022-06).

But this is not the case. So I'm looking it up and I find tips on the net which involve adding new entries to "Available Software Sites" in the preferences. And sometimes it works and sometimes not and then I need to download and install the new version.

All this is not a big deal, but it is still the most weird and time-consuming upgrade process for any software I'm using. It would be nice if this could be improved.

I'm using the "Eclipse IDE for Enterprise Java and Web Developers" variant.

**Comment by vogella** [comment]
Recent Eclipse version should have a "latest" url under help -> install new software. https://download.eclipse.org/releases/latest If that is present the update check should find new versions very 3 months.

If this entry is not present please add it, IIRC it was added a few years ago by default.

**Comment by jubax** [comment]
Okay, thanks. I can confirm that upgrading to 2022-06 works fine with a fresh install of 2022-03. I'm not sure why the upgrade did not work correctly before (AFAIK "latest" was actually there).
