### ISSUE TITLE
Eclipse 2022-06 crash even after reinstall... due to code signing.

### ISSUE THREAD

**Issue by bric3** [eclipse-platform/.github#36]
![image](https://user-images.githubusercontent.com/803621/177171475-220da17b-048c-42bd-bf3a-2967eda95789.png)

Even re-installing was broken again.

```text
https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2022-06/R/eclipse-rcp-2022-06-R-macosx-cocoa-x86_64.dmg&r=1
```

```text
Exception Type:  EXC_CRASH (SIGKILL (Code Signature Invalid))
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: CODESIGNING 1 
```

It seems an old trick fixed the problem until it comes again.

```shell
$ codesign --force --deep --sign - /Applications/Eclipse\ RCP.app
```

**Comment by akurtakov** [comment]
@lshanmug have you seen this one?

**Comment by lshanmug** [comment]
> https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2022-06/R/eclipse-rcp-2022-06-R-macosx-cocoa-x86_64.dmg&r=1

I tried the build and it works fine for me. Did you see the crash on startup? Have you installed any additional plugins?

**Comment by bric3** [comment]
Yeah I possibly installed other plugins, one or two, but I didn't reinstall them, and it was happening again, so possibly there was some leftover files.

And yes, this happened on startup. It happened almost at every launch in June / early July, but it doesn't anymore. 
So I don't know what to say, I know I'm not alone in this case though.

**Comment by jukzi** [comment]
Please add crashdump `hs_err_pid*.log`

**Comment by jukzi** [comment]
closing due to missing info
