### ISSUE TITLE
JAVA EE PERSPECTIVE NOT PRESENT in eclipse

### ISSUE THREAD

**Issue by DeepakLalchandani** [eclipse-platform/.github#39]
Hi,
    JAVA EE PERSPECTIVE NOT PRESENT in eclipse version for java developers ( java -2022-03 )

There is no tomcat server view in the latest Eclipse IDE for Java Developers – 2022-03 edition.

Moreover tomcat server is started from windows services.

When i run http://localhost:8080/MyProjectTool, i get below error.

Status Report Message The requested resource [/MyProjectTool/] is not available 

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Please help.

**Comment by jonahgraham** [comment]
Java EE perspective comes as part of Eclipse IDE for Enterprise Java and Web Developers.

Please try using that package instead.

**Comment by DeepakLalchandani** [comment]
I want to change the perspective in my eclipse version for java developers ( java -2022-03 ). 

I have a project in my eclipse version for java developers ( java -2022-03 ). How to change the perspective here

**Comment by mickaelistria** [comment]
Window > Perspective; or Ctrl+3 > Perspective, or on the top-right of the workbench there is a perspective switcher...
