### ISSUE TITLE
Enable the wiki + discussions?

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/.github#4]
Can we enable the Wiki + Discussions for all projects under this umbrealla or should we enable that on the individual repos?

**Comment by vogella** [comment]
+1 as platform project lead, please open a issue for the help center of the foundation for this.

**Comment by akurtakov** [comment]
@vogella Project leads can do that via the settings of each repo.

**Comment by vogella** [comment]
Wiki yes, also done by me now but discussion I don't see the option in the UI.

**Comment by laeubi** [comment]
Discussions must be requested by a project lead AFAIK from the service-desk.

**Comment by vogella** [comment]
> Discussions must be requested by a project lead AFAIK from the service-desk.

Just link to this issue in your request, in which the project lead gave his permission. I can also do it later, if you do not want do / do not have the time..

**Comment by mickaelistria** [comment]
Wikis have a lot of drawbacks: they're often out of date, not wrll maintained, their contributions are not tracked so well...
I'd rather see wiki avoided and dev doc placed directly in relevant Got repo together with code and regular doc.

**Comment by jonahgraham** [comment]
By tying the wiki + discussions into one bug neither item seems to have got any traction.

Was there any objection to discussions? Would that be seen as a replacement for Eclipse Forums?

**Comment by vogella** [comment]
Wiki is enabled, nobody seems to care enough to act upon https://github.com/eclipse-platform/.github/issues/4#issuecomment-1111842191

**Comment by laeubi** [comment]
Hi Lars, maybe cause of your comment

> I can also do it later, if you do not want do / do not have the time..

so everyone is waiting for this "later"? :-)

**Comment by vogella** [comment]
> Hi Lars, maybe cause of your comment
> 
> > I can also do it later, if you do not want do / do not have the time..
> 
> so everyone is waiting for this "later"? :-)

[To avoid futher waste of time: ](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1371)

**Comment by vogella** [comment]
Discussion enabled
