### ISSUE TITLE
External snippet files with Java 18

### ISSUE THREAD

**Issue by uhoefel** [eclipse-platform/.github#42]
From Oracles [description](https://docs.oracle.com/en/java/javase/18/code-snippet/index.html) on how to use external snippet files:

> The first example shows a directory named src, containing the source for a class p.Main, an image icon.png in the doc-files subdirectory, and a file for external snippets, Snippets.java, in the snippet-files directory. The presence of doc-files/icon.png is just to show the similarity between the use of doc-files and snippet-files directories. No additional options are required for the Standard Doclet to locate the external snippets in this example.
```
src
└── p
    ├── Main.java
    ├── doc-files
    │   └── icon.png
    └── snippet-files
        └── Snippets.java
```
> Note: some build systems may (incorrectly) treat files in the snippet-files directory as part of the enclosing package hierarchy, even though snippet-files is not a valid Java identifier and cannot be part of a Java package name. The local snippet-files directory cannot be used in these cases.

If I try this in eclipse I get
![image](https://user-images.githubusercontent.com/4885222/181621140-9fdd3b3f-0002-4e7c-bd9c-c59632b390ec.png)
and
![image](https://user-images.githubusercontent.com/4885222/181621313-2ed6a85d-b967-4979-a4ea-6a60f3a33d65.png)

Is this reasonably fixable? The other solution listed by Oracle requires setting `--snippet-path` which I'd rather avoid, if possible.

**Comment by mickaelistria** [comment]
Can you please report this issue to https://github.com/eclipse-jdt/eclipse.jdt.core/issues ? Unfortunately, we cannot transfer the issue to the repo so a new report is necessary.

**Comment by uhoefel** [comment]
I've opened a [new issue](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/276) there.

**Comment by mickaelistria** [comment]
Thanks!
