### ISSUE TITLE
IDE launcher duplicated

### ISSUE THREAD

**Issue by o-alquimista** [eclipse-platform/.github#49]
You can see in the screenshot below that I have an Eclipse launcher (the one with the Eclipse logo). When clicked, it spawns a new item instead (the one without an icon).

![Captura de tela de 2022-08-15 12-35-49](https://user-images.githubusercontent.com/25424263/184666675-37928060-ec00-44d9-93f6-81be3b8c3ad1.png)

This is the `.desktop` file I have at `~/.local/share/applications/`:

```ini
[Desktop Entry]
Name=Eclipse Platform
Exec=/home/user/Eclipse/ide/eclipse/eclipse %u
NoDisplay=false
Icon=/home/user/Eclipse/ide/eclipse/icon.xpm
Type=Application
MimeType=x-scheme-handler/eclipse+command;x-scheme-handler/xdebug;
```

- Eclipse version: 2022-06 (4.24) Build id: I20220607-0700 (installed in my home folder by the Eclipse Installer)
- GNOME 42.3 on Wayland
- Fedora 36 Workstation (amd64)

**Comment by mickaelistria** [comment]
I don't have this problem. This is what my `eclipse.desktop` file looks like
```ini
[Desktop Entry]
Name=Eclipse SDK (local)
Comment=Eclipse SDK
Exec=/home/mistria/apps/eclipse-SDK/eclipse %u
Icon=/home/mistria/apps/eclipse-SDK/icon.xpm
Terminal=false
Type=Application
StartupNotify=true
Categories=Development;
MimeType=x-scheme-handler/eclipse+mpc;x-scheme-handler/eclipse+command;
```
The `Terminal=false` may be interesting.

**Comment by o-alquimista** [comment]
> The Terminal=false may be interesting.

Tried that now, and it didn't work.

**Comment by akurtakov** [comment]
Is this one still relevant?
