### ISSUE TITLE
Eclipse 2022-03 Window -> Preferences -> Java -> Appearance : Compress all package name segments not compressing packages

### ISSUE THREAD

**Issue by jonmichaelpeedin** [eclipse-platform/.github#5]
Upon recently upgrading to 2022-03 I have noticed that the "Compress all package name segments, except the final segment" is not compressing the packages in my project. I have attempted to use the compression pattern '.', '0', and '1' with no success. 

I also attempted to use the "Abbreviate package names" and that was not doing anything to the package names that I specified either. 

![E2022-03_CompressPackageIssue](https://user-images.githubusercontent.com/48923241/165824795-1ef1aa6d-e4d9-47ff-a31e-b23bacb7def4.PNG)

**Comment by jonmichaelpeedin** [comment]
The previous version I was using was 2020_12 where it worked as expected

**Comment by mickaelistria** [comment]
I think it is https://bugs.eclipse.org/bugs/show_bug.cgi?id=579170

**Comment by mickaelistria** [comment]
Please try the latest Eclipse SDK builds from download.eclipse.org/eclipse/ and report whether you can reproduce this issue or not.

**Comment by jonmichaelpeedin** [comment]
The version I was referring to in my OP was the latest stable release of 2022-03 where it was an issue. I have even tried the latest Integration Build (https://download.eclipse.org/eclipse/downloads/drops4/I20220501-1800/) where it was still an issue.

**Comment by mickaelistria** [comment]
2022-03 is more than Eclipse Platform and some other projects can cause bugs.
However, if you can reproduce the issue with https://download.eclipse.org/eclipse/downloads/drops4/I20220501-1800/ , then it's indeed a bug and thanks for confirming it. The project that takes care of providing those package is https://github.com/eclipse-jdt . Can you please report the issue to https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/ as we cannot transfter issues between projects from different owners/orgs ?

**Comment by jonmichaelpeedin** [comment]
Update to my previous statement: I deleted the .project file for my project and it displayed properly, however when i converted it back to a faceted project the issue comes back. Please see attached screenshots

![E2022-03_CompressPackageIssue_1](https://user-images.githubusercontent.com/48923241/166268891-30ea2356-af70-4f99-bfc1-23a77e96be48.PNG)

![E2022-03_CompressPackageIssue_2](https://user-images.githubusercontent.com/48923241/166268912-0dd087f4-8a9b-4c67-8405-90d5f2a3fbc7.PNG)

![E2022-03_CompressPackageIssue_3](https://user-images.githubusercontent.com/48923241/166268959-7264cebb-6e07-4e1c-85e5-3928b79fccd7.PNG)

![E2022-03_CompressPackageIssue_4](https://user-images.githubusercontent.com/48923241/166268984-20865617-5d99-451a-880d-cb0dda816005.PNG)
