### ISSUE TITLE
Eclipse 2022-06 crashes under Linux openSUSE 15.4 (KDE Plasma)

### ISSUE THREAD

**Issue by holle** [eclipse-platform/.github#52]
Eclipse 2022-03 (updated to 2022-06) as well as a fresh 2022-06 install with an empty working directory crashes under Linux openSUSE 15.4 (KDE Plasma/X11).
No (meaningful) logmessages are being generated.
Happens with the default JRE/Xmx and adopted:
JDK11 (Oracle) 8GB
JDK1.8 (Oracle) 6GB

The (a) crash can be directly forced by simply accessing the Eclipse Marketplace and waiting a moment.
It is also impossible to install any extension from the Marketplace using Drag and Drop (Install Button).

It also crashes when using the Java editor. Suddenly the editor becomes unresponsive, followed by a crash.

The crash does not open a "crashed app" window, it simply disappears.

setting these variables:
```bash
export MALLOC_CHECK_=0
unset GDK_NATIVE_WINDOWS
export SWT_GTK3=1
export GIT_SSH=/usr/bin/ssh
```
or **_not_** does not seem to have any (apart from the file open dialog L&F) effects.

Attempting to use the SpringToolSuite4.15.3 shows the same behavior regarding the Marketplace access. No further tests have been made with STS.

**Comment by holle** [comment]
Hi @akurtakov,

thanks for the quick reply. It looks as if in fact I am running the affected webkitgtk version:
```bash
libwebkit2gtk-4_1-0-2.36.5-150400.4.9.1.x86_64
libwebkit2gtk-4_0-37-2.36.5-150400.4.9.1.x86_64
```
I will attempt to downgrade the rpms manually.

Cheers,
Holger

**Comment by holle** [comment]
Howto/Tip:
This "Hack" worked for me (thanks again to @akurtakov for pointing out the real problem):

Downloaded the "old" rpms (ymmv):

- https://download.opensuse.org/distribution/leap/15.4/repo/oss/x86_64/libwebkit2gtk-4_0-37-2.36.0-150400.2.13.x86_64.rpm
- https://download.opensuse.org/distribution/leap/15.4/repo/oss/x86_64/libwebkit2gtk-4_1-0-2.36.0-150400.2.13.x86_64.rpm
- https://download.opensuse.org/distribution/leap/15.4/repo/oss/x86_64/libjavascriptcoregtk-4_0-18-2.36.0-150400.2.13.x86_64.rpm
- https://download.opensuse.org/distribution/leap/15.4/repo/oss/x86_64/libjavascriptcoregtk-4_1-0-2.36.0-150400.2.13.x86_64.rpm
- https://download.opensuse.org/distribution/leap/15.4/repo/oss/noarch/WebKit2GTK-4.0-lang-2.36.0-150400.2.13.noarch.rpm
- https://download.opensuse.org/distribution/leap/15.4/repo/oss/noarch/WebKit2GTK-4.1-lang-2.36.0-150400.2.13.noarch.rpm
- https://download.opensuse.org/distribution/leap/15.4/repo/oss/x86_64/webkit2gtk-4_0-injected-bundles-2.36.0-150400.2.13.x86_64.rpm
- https://download.opensuse.org/distribution/leap/15.4/repo/oss/x86_64/webkit2gtk-4_1-injected-bundles-2.36.0-150400.2.13.x86_64.rpm

Then unpacked all those RPMs "next" to my eclipse installation folder (mine is /workspace/eclipse-binaries):
```bash
cd /workspace/eclipse-binaries
rpm2cpio <RPM> | cpio -id
# rinse and repeat for each rpm
```
The above created the "normal" file structure usr/lib usr/lib64 usr/share etc...
Then I added the .../usr/lib64 path as an ld preload to my startup script:
```bash
#!/bin/sh
#. ~/bin/setup-java11-env.sh
export GIT_SSH=/usr/bin/ssh
export LD_LIBRARY_PATH=/workspace/eclipse-binaries/usr/lib64
cd /workspace/eclipse-binaries/eclipse-jee-2022-06-R
./eclipse $* &
```
And now everything seems to work properly :-)

Hope this helps others until we have a fixed version available.
Cheers,
Holger

**Comment by akurtakov** [comment]
Make sure you report this to suse devs.

**Comment by holle** [comment]
The openSUSE Team is already aware and working on a solution:
https://bugzilla.opensuse.org/show_bug.cgi?id=1202169
