### ISSUE TITLE
https://wiki.eclipse.org/Platform/How_to_Contribute outdated

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/.github#54]
The Document is linked from https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md but outdated.

Especially the the sections
https://wiki.eclipse.org/Platform/How_to_Contribute#.5B3.1.5D_Use_Gerrit_for_clone.2Fpush
https://wiki.eclipse.org/Platform/How_to_Contribute#Creating_a_Gerrit_review_or_a_patch

* we do not use gerrit anymore.
*  section 4 https://wiki.eclipse.org/Platform/How_to_Contribute#Contributing_Code could be replaced by https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md

**Comment by akurtakov** [comment]
It's a wiki so everyone can edited. It's still best to enhance  https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md thought. Thus I edited the wiki page and removed all outdated information and added general note at the top with link to CONTRIBUTING.md.

**Comment by akurtakov** [comment]
I'll actually close this one. Please open PRs if smth is missing in contributing.md.
