### ISSUE TITLE
unsigned content dialog is misleading

### ISSUE THREAD

**Issue by maxandersen** [eclipse-platform/.github#59]
when instaling a plugin from https site it is quite disturbing to get this dialog:

![2022-08-31_10-12-42](https://user-images.githubusercontent.com/54129/187628300-174e1ab7-229a-4578-ac5e-fd7c64705f88.png)

this dialog should at least state what https site it is being installed from.

Any in development plugin will not be signed but you would be fine if you at least are informed what source https origin it is coming from.

**Comment by merks** [comment]
That information is not known/tracked at this point, and we have no plans to the implement tracking such details. 

If you wish to contribute a PR for that, you can do so here:

https://github.com/eclipse-equinox/p2
