### ISSUE TITLE
How to remove Eclipse Test Menus and Tabs

### ISSUE THREAD

**Issue by autumoswitzerland** [eclipse-platform/.github#62]
Eclipse shows eclipse developer test menus and tabs.

An eclipse developer gave me a link to an unofficial eclipse distribution once. 

Since then I have Test menus and tabs shown in eclipse everywhere. I just installed a new clean latest eclipse version (2022-06 - jee edition) and I transferred my installed software and my eclipse workspace and the test entries show up again.

How can I permanently remove these test entries?

See attached image too.
![eclipse](https://user-images.githubusercontent.com/100039855/190204078-96d3b740-ae86-4d77-a817-8b56395c5982.png)

**Comment by akurtakov** [comment]
Go to Help/About Eclipse SDK/Installation details/Features and give us the list of installed features and we can try to figure out what you need to uninstall.

**Comment by autumoswitzerland** [comment]
Here's the list. Very appreciated!

![Bildschirmfoto 2022-09-14 um 18 06 45](https://user-images.githubusercontent.com/100039855/190205971-3c3367d1-a677-4387-8c4e-4ba392dff2b3.png)
![Bildschirmfoto 2022-09-14 um 18 06 56](https://user-images.githubusercontent.com/100039855/190205978-6f5baa6a-3ff3-4945-97f9-d3df06bf46eb.png)

**Comment by mickaelistria** [comment]
Just uninstall the 1st feature `org.eclipse.sdk.tests`

**Comment by autumoswitzerland** [comment]
Thanks. Sorry to ask: But how to de-install a feature?

**Comment by akurtakov** [comment]
Remove org.eclipse.sdk.examples too. You can do that in the first tab "Installed Software". Look for tests and examples and at the botton there is Uninstall button when you have something selected.

**Comment by autumoswitzerland** [comment]
Those ?
![Bildschirmfoto 2022-09-14 um 18 16 21](https://user-images.githubusercontent.com/100039855/190207862-787b7e10-5a21-4b51-b291-bf2bce6b768d.png)

**Comment by akurtakov** [comment]
> Those ? ![Bildschirmfoto 2022-09-14 um 18 16 21](https://user-images.githubusercontent.com/100039855/190207862-787b7e10-5a21-4b51-b291-bf2bce6b768d.png)

Yes.

**Comment by autumoswitzerland** [comment]
Looks good so far. Thanks!
