### ISSUE TITLE
eclipse installer eclipse-inst-jre-win64.exe is possibly infected with a malware.

### ISSUE THREAD

**Issue by john3825** [eclipse-platform/.github#67]
**eclipse installer for 2022-9r** : [eclipse-inst-jre-win64.exe](https://www.eclipse.org/downloads/download.php?file=/oomph/epp/2022-09/R/eclipse-inst-jre-win64.exe&mirror_id=1248) 
`sha512:241eeea731ab1f80e07b598a14a2c2591b0a3538e48bc78d37e30176c054d437545e455341a74f478a2990c7419d5b0241327211edd25d6b8de8925d10abae46` may be infected with a virus from the [virustoal scan result](https://www.virustotal.com/gui/file/1d57ba7cf596601a1096709fcf9839d069114bb2f0585ae7f54ee8d5f725db8e?nocache=1).

- **`sha256:1d57ba7cf596601a1096709fcf9839d069114bb2f0585ae7f54ee8d5f725db8e`**
- **file: eclipse-inst-jre-win64 (1).exe**
- **date: 2022-09-25 16:36:26 UTC**

**detected  by Cybereason: Malicious.3e8304**

**Possible reasons**
[malicious behavior](https://www.virustotal.com/gui/file/1d57ba7cf596601a1096709fcf9839d069114bb2f0585ae7f54ee8d5f725db8e/behavior)
- Process Creation Using Sysnative Folder
- Wow6432Node CurrentVersion Autorun Keys Modification

Please check the file for malware. It seems like from heuristic scan because of the name.

**Comment by mickaelistria** [comment]
This issue must be reported to https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Oomph

**Comment by john3825** [comment]
I reported [https://bugs.eclipse.org/bugs/show_bug.cgi?id=580813](https://bugs.eclipse.org/bugs/show_bug.cgi?id=580813)

**Comment by mickaelistria** [comment]
Thank you!
