### ISSUE TITLE
Incorrect Chinese option name for 'Close All'

### ISSUE THREAD

**Issue by iraidaa** [eclipse-platform/.github#68]
Hello,

I want to report a translating issue for Close All Tabs in Chinese. 

If you open 2  or more tabs and right-click one of the tabs, you'll get an incorrect Chinese option name for 'Close All'. As I understand, it shoud be "关闭全部" or “全部关闭” ('close all')，but it is "关闭关闭“ ('close close'). Thanks @SSSDNSY for the translation.

Thank you.

**Comment by akurtakov** [comment]
Translations are handled by Babel project which provides a webapp to improve translations. Go to https://babel.eclipse.org/babel/ and contribute

**Comment by akurtakov** [comment]
I'm closing this issue as the fix has to come through babel.
