### ISSUE TITLE
Eclipse E4 Macros Incubation

### ISSUE THREAD

**Issue by kPYKx7Ddw4n1aIKZ** [eclipse-platform/.github#69]
The Eclipse [macro plugin](https://marketplace.eclipse.org/content/eclipse-macros-incubation) no longer works with newer eclipse versions.
As a comment there says, it requires a bundle in newer versions that have been removed.

I've already tried to [contribute a change](https://git.eclipse.org/r/c/e4/org.eclipse.e4.ui/+/196004) in the [original repository](https://git.eclipse.org/r/plugins/gitiles/e4/org.eclipse.e4.ui/+/refs/heads/master/bundles/org.eclipse.e4.core.macros/) but it doesn't seem to be maintained.

Can this plugin be added to this organization?
Can the problems with this plugin be fixed and the plugin get released again?

**Comment by mickaelistria** [comment]
> Can this plugin be added to this organization? Can the problems with this plugin be fixed and the plugin get released again?

I don't think the fact that it's not maintained is a positive sign that the plugin should be added to the organization. Maybe the best path forward is the opposite: if there is no-one in Eclipse project willing to maintain it, we should remove it and this plugin should then be hosted (eg code moved/forked) into the Eclipse macro plugin?

Out of curiosity, what are the main actions you need macros for?

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
I think I will fork it then and add a few improvements.

I mainly used it to run a few UI commands in a row.
However, this plugin seems to be very limited, especially since one can only create one macro, and it doesn't seem to be very popular either.

Maybe that's why it wasn't further developed and not merged into eclipse.

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
I forked it [here](https://github.com/kPYKx7Ddw4n1aIKZ/eclipse-macro-plugin) and released it [here](https://marketplace.eclipse.org/content/eclipse-macro-plugin).
