### ISSUE TITLE
Layout window doesn't open with WindowBuilder Eclipse 2022-03

### ISSUE THREAD

**Issue by JuanitoMora** [eclipse-platform/.github#71]
I just create a new project with WindowBuilder for a homework,  then I push in tab Desing and the Eclipse show me a text that Unable to load *.wbp-component.xml description.
[report-20221010-224904.zip](https://github.com/eclipse-platform/.github/files/9751050/report-20221010-224904.zip)

**Comment by akurtakov** [comment]
This looks like WindowBuilder problem which should be reported against that project https://github.com/eclipse/windowbuilder/issues . I'm closing this one as there is not much Eclipse Platform can do about this issue.

**Comment by JuanitoMora** [comment]
Okey Akurtakov, thank you very much

**Comment by JuanitoMora** [comment]
I found a solution, in this link of StackOverflow at the point three
https://stackoverflow.com/questions/69927269/windowbuilder-was-not-able-to-show-the-gui-unable-to-load-wbp-component-xml-d
