### ISSUE TITLE
Update Tycho extenstion to 2.7.2

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/.github#8]
Dependabot handles updates of regular poms but not in .mvn/extensions.xml.

**Comment by laeubi** [comment]
According to the dependabot source it should do also handle extensions.xml, so maybe a bug or simply dependabot is lazy here :-)

**Comment by akurtakov** [comment]
Dependabot chokes on pomless builds thus the config is to run on eclipse-platform-parent only (https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/.github/dependabot.yml). There are also no config in the separate repositories where .mvn/extensions.xml, honestly I haven't tried configuring dependabot for extensions.xml in all repos - never found the time to try whether it can check it only in order to ignore the pomless failure.

**Comment by akurtakov** [comment]
I just pushed https://github.com/akurtakov/eclipse.platform.releng.aggregator/commit/f52e7bab06df3a97fd662dc75f459737d505e7f7 to try whether handling .mvn would work but it doesn't look so.

**Comment by akurtakov** [comment]
This one is done.

**Comment by iloveeclipse** [comment]
@akurtakov : just stumbled over this while looking on [fd leak in tycho](https://github.com/eclipse/tycho/issues/965). 
I don't see file `.mvn/extensions.xml` in SWT repo. Is this on purpose? What does this tycho extensions thing do?

**Comment by akurtakov** [comment]
> @akurtakov : just stumbled over this while looking on [fd leak in tycho](https://github.com/eclipse/tycho/issues/965). I don't see file `.mvn/extensions.xml` in SWT repo. Is this on purpose? What does this tycho extensions thing do?

`.mvn/extensions.xml` is only needed then there are pomless builds. Due to the complicated manner of swt bundles and limited number of them there is no win if we go pomless - thus no such file.

**Comment by laeubi** [comment]
This would be required to compile SWT pomless (or more specific: antless as a first step) as currently the compile is performed by ant scripts invoked by maven:

- https://github.com/eclipse/tycho/issues/632
