### ISSUE TITLE
Inactive committers cleanup

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/.github#92]
There have been 3 years since last cleanup of inactive committers https://bugs.eclipse.org/bugs/show_bug.cgi?id=573495 . It's time to do it again. Our semi automated script is run at https://ci.eclipse.org/releng/job/Inactive-committers-platform/47/artifact/inactiveCommitters.txt and points to the following committers that had no commit in the last 2 years:
- [ ] Bogdan Gheorghe
- [ ] Brian de Alwis
- [ ] Jonas Helming
- [ ] Michael Rennie
- [x] Mike Wilson
- [ ] Patrik Suzzi
- [ ] Paul Pazderski
- [ ] Silenio Quarti
- [ ] Steve Northover
- [x] Szymon Ptaszkiewicz
- [ ] Till Brychcy

Please state your will to keep your committership here by March 17th  2023. 

The script is not perfect and I've fixed few false positives in it but I may have missed some - if that's the case please point me to a commit of yours so I can look why the script didn't pick it up.

**Comment by theMcQ** [comment]
I wish to retain my commit rights.

**Comment by sptaszkiewicz** [comment]
Same here, I wish to retain my commit rights.

**Comment by akurtakov** [comment]
I'm retiring now the following committers:
Bogdan Gheorghe
Brian de Alwis
Jonas Helming
Michael Rennie
Patrik Suzzi
Paul Pazderski
Silenio Quarti
Steve Northover
Till Brychcy

**Comment by akurtakov** [comment]
Thank you all for the contributions! I would be really happy to see as many of you as possible coming back with PRs and remember that for retired committers we have fast-track to nomination again.
